name=I2Connect VEML7700
version=1.0.0
author=PTSolns
maintainer=PTSolns <support@ptsolns.com>
sentence=Library for the PTSolns I2Connect: VEML7700 Light and Lux sensor.
paragraph=This library provides a simple interface to read ambient light data (in lux) from the VEML7700 sensor module over I2C. Designed seamlessly for the I2Connect ecosystem.
category=Sensors
url=https://github.com/PTSolns/I2Connect_VEML7700
architectures=*
includes=PTSOLNS_I2CONNECT_VEML7700.h
